import * as wasm from "lincoln_wasm";

const Program = wasm.WasmProgram;
const CodeRef = wasm.WasmCodeRef;
const GroupRef = wasm.WasmGroupRef;
const prog = Program.new();
var v = prog.add_return(0);
v = prog.add_call(CodeRef.new_extern(2), 2, {"group": 0});
v = prog.add_return(1);
v = prog.add_jump(CodeRef.new_extern(6), "acb");
v = prog.add_jump(CodeRef.new_entry(0), "ba");
v = prog.add_jump(CodeRef.new_entry(1), "aecdb");
v = prog.add_jump(CodeRef.new_entry(2), "ba");
v = prog.add_jump(CodeRef.new_entry(0), "cba");
v = prog.add_call(CodeRef.new_extern(1), 1, GroupRef.new(1));
v = prog.add_call(CodeRef.new_extern(4), 1, GroupRef.new(2));
v = prog.add_call(CodeRef.new_extern(7), 2, GroupRef.new(3));
v = prog.add_jump(CodeRef.new_entry(8), "ba");
v = prog.add_call(CodeRef.new_extern(6), 1, GroupRef.new(4));
v = prog.add_jump(CodeRef.new_entry(10), "ba");
v = prog.add_call(CodeRef.new_entry(11), 3, GroupRef.new(5));
v = prog.add_call(CodeRef.new_extern(4), 1, GroupRef.new(6));
v = prog.add_call(CodeRef.new_extern(5), 2, GroupRef.new(7));
v = prog.add_call(CodeRef.new_entry(14), 2, GroupRef.new(8));
v = prog.add_jump(CodeRef.new_entry(15), "cba");
v = prog.add_jump(CodeRef.new_entry(16), "aecdb");
v = prog.add_call(CodeRef.new_extern(1), 1, GroupRef.new(9));
v = prog.add_jump(CodeRef.new_entry(20), "cba");
v = prog.add_call(CodeRef.new_entry(21), 3, GroupRef.new(2));

v = prog.add_extern_value(zero);
v = prog.add_extern_value(copy_int);
v = prog.add_extern_value(eq);
v = prog.add_extern_value(one);
v = prog.add_extern_value(drop_int);
v = prog.add_extern_value(minus);
v = prog.add_extern_value(mul);

v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(18));
prog.add_group_entry(v, CodeRef.new_entry(22));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(5));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_extern(3));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(3));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(9));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_extern(0));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(12));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(13));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(17));
prog.add_group_entry(v, CodeRef.new_entry(14));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(19));
v = prog.add_empty_group();
prog.add_group_entry(v, CodeRef.new_entry(17));
v = 10;
