[package]
name = "lincoln_common"
version = "0.1.0"
authors = ["Joe Ren <earthengine@gmail.com>"]
edition = "2018"
description = "Common functions, traits for Lincoln"
license = "MIT"
homepage = "https://github.com/earthengine/Lincoln"

[dependencies]
